### ISSUE TITLE
метод installGame в классе Player обнуляет время игры при установке

### ISSUE THREAD

**Issue by Maxim-GT** [LiubovSokolova89/GameActivityTracking#6]
# Описание
Метод installGame в классе Player обнуляет время игры при установке, проигранное время им не учитывается

# Локализация дефекта

https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/main/java/ru/netology/Player.java#L24

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/main/java/ru/netology/Player.java) в IDEA 
1. Запустить тест shouldSumGenreIfOneGame в классе [PlayerTest](https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/test/java/ru/netology/PlayerTest.java)
1. Изучить полученные логи

*Ожидаемый результат:* тест пройден
*Фактический результат:* AssertionFaildError

# Скриншот
![2022-09-14_09-41-05](https://user-images.githubusercontent.com/107297821/190047597-4c7eda57-46b2-43e8-9f67-493790531c77.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by LiubovSokolova89** [comment]
Corrected
