### ISSUE TITLE
Метод mostPlayerByGenre не проверяет, запускалась ли установленнуая игра

### ISSUE THREAD

**Issue by Maxim-GT** [LiubovSokolova89/GameActivityTracking#9]
# Описание
Метод mostPlayerByGenre в классе Player возвращает null 
# Локализация дефекта

https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/main/java/ru/netology/Player.java) в IDEA 
1. Запустить тест shouldSumGenreIfOneGame в классе [PlayerTest](https://github.com/LiubovSokolova89/GameActivityTracking/blob/47e9768c6148f5531d01b74b421109aea1ca4594/src/test/java/ru/netology/PlayerTest.java)
1. Изучить полученные логи

*Ожидаемый результат:* тест не проходит так как в игру не играли
*Фактический результат:* тест проходит без проверки на запуск установленной игры

# Скриншот

![2022-09-29_18-38-04](https://user-images.githubusercontent.com/107297821/193021869-c2d0aa56-fa36-49c7-b297-c20080695625.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by LiubovSokolova89** [comment]
Corrected
